[Logger]
Level = "DEBUG"
File = ""
Fields = [
    "prefix"
]

[IngestPoints]

    [IngestPoints.redis]
    Type = "redis"
    Enabled = false
    Host = "localhost"
    Port = 6379
    Pattern = "logthing:*"

    [IngestPoints.tls-in]
    Type = "tls"
    Enabled = true
    Port = 8001
    Certificate = "certs/server.pem"
    Key = "certs/server.key"

    [IngestPoints.https]
    Type = "https"
    Enabled = false
    Port = 8002
    Endpoint = "/v1/ingest"

[DigestPoints]

    [DigestPoints.redis-out]
    Type = "redis"
    Enabled = true
    Host = "localhost"
    Port = 6379
    Pattern = "logthing:{{logId}}"
    Ingests = ["tls-in"]

